spring:
  application:
    name: classe-service-wflux

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/service_classe_2dbc
    username: postgres
    password: passer

  sql:
    init:
      platform: postgres
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      #mode: always

server:
  port: 8091